# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.2.0
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _qft
else:
    import _qft

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _qft.delete_SwigPyIterator

    def value(self):
        return _qft.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _qft.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _qft.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _qft.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _qft.SwigPyIterator_equal(self, x)

    def copy(self):
        return _qft.SwigPyIterator_copy(self)

    def next(self):
        return _qft.SwigPyIterator_next(self)

    def __next__(self):
        return _qft.SwigPyIterator___next__(self)

    def previous(self):
        return _qft.SwigPyIterator_previous(self)

    def advance(self, n):
        return _qft.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _qft.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _qft.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _qft.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _qft.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _qft.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _qft.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _qft:
_qft.SwigPyIterator_swigregister(SwigPyIterator)
class vector_double(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _qft.vector_double_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _qft.vector_double___nonzero__(self)

    def __bool__(self):
        return _qft.vector_double___bool__(self)

    def __len__(self):
        return _qft.vector_double___len__(self)

    def __getslice__(self, i, j):
        return _qft.vector_double___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _qft.vector_double___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _qft.vector_double___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _qft.vector_double___delitem__(self, *args)

    def __getitem__(self, *args):
        return _qft.vector_double___getitem__(self, *args)

    def __setitem__(self, *args):
        return _qft.vector_double___setitem__(self, *args)

    def pop(self):
        return _qft.vector_double_pop(self)

    def append(self, x):
        return _qft.vector_double_append(self, x)

    def empty(self):
        return _qft.vector_double_empty(self)

    def size(self):
        return _qft.vector_double_size(self)

    def swap(self, v):
        return _qft.vector_double_swap(self, v)

    def begin(self):
        return _qft.vector_double_begin(self)

    def end(self):
        return _qft.vector_double_end(self)

    def rbegin(self):
        return _qft.vector_double_rbegin(self)

    def rend(self):
        return _qft.vector_double_rend(self)

    def clear(self):
        return _qft.vector_double_clear(self)

    def get_allocator(self):
        return _qft.vector_double_get_allocator(self)

    def pop_back(self):
        return _qft.vector_double_pop_back(self)

    def erase(self, *args):
        return _qft.vector_double_erase(self, *args)

    def __init__(self, *args):
        _qft.vector_double_swiginit(self, _qft.new_vector_double(*args))

    def push_back(self, x):
        return _qft.vector_double_push_back(self, x)

    def front(self):
        return _qft.vector_double_front(self)

    def back(self):
        return _qft.vector_double_back(self)

    def assign(self, n, x):
        return _qft.vector_double_assign(self, n, x)

    def resize(self, *args):
        return _qft.vector_double_resize(self, *args)

    def insert(self, *args):
        return _qft.vector_double_insert(self, *args)

    def reserve(self, n):
        return _qft.vector_double_reserve(self, n)

    def capacity(self):
        return _qft.vector_double_capacity(self)
    __swig_destroy__ = _qft.delete_vector_double

# Register vector_double in _qft:
_qft.vector_double_swigregister(vector_double)
class LorentzVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, ix, iy, iz, it):
        _qft.LorentzVector_swiginit(self, _qft.new_LorentzVector(ix, iy, iz, it))

    def x(self):
        return _qft.LorentzVector_x(self)

    def y(self):
        return _qft.LorentzVector_y(self)

    def z(self):
        return _qft.LorentzVector_z(self)

    def t(self):
        return _qft.LorentzVector_t(self)

    def e(self):
        return _qft.LorentzVector_e(self)

    def perp(self):
        return _qft.LorentzVector_perp(self)

    def perp2(self):
        return _qft.LorentzVector_perp2(self)

    def mass(self):
        return _qft.LorentzVector_mass(self)

    def mass2(self):
        return _qft.LorentzVector_mass2(self)

    def p(self):
        return _qft.LorentzVector_p(self)

    def phi(self):
        return _qft.LorentzVector_phi(self)

    def theta(self):
        return _qft.LorentzVector_theta(self)

    def cosTheta(self):
        return _qft.LorentzVector_cosTheta(self)

    def eta(self):
        return _qft.LorentzVector_eta(self)

    def PrintPtEtaPhiM(self):
        return _qft.LorentzVector_PrintPtEtaPhiM(self)

    def PrintPEtaPhiE(self):
        return _qft.LorentzVector_PrintPEtaPhiE(self)

    def PrintXYZT(self):
        return _qft.LorentzVector_PrintXYZT(self)

    def Print(self):
        return _qft.LorentzVector_Print(self)

    def __add__(self, right):
        return _qft.LorentzVector___add__(self, right)

    def __sub__(self, right):
        return _qft.LorentzVector___sub__(self, right)

    def __mul__(self, right):
        return _qft.LorentzVector___mul__(self, right)
    __swig_destroy__ = _qft.delete_LorentzVector

# Register LorentzVector in _qft:
_qft.LorentzVector_swigregister(LorentzVector)

def testLorentzVectors():
    return _qft.testLorentzVectors()

def getQ_T3_NC(pdgID, q, t3, NC):
    return _qft.getQ_T3_NC(pdgID, q, t3, NC)
class Particle(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, p4, pdgID):
        _qft.Particle_swiginit(self, _qft.new_Particle(p4, pdgID))

    def p4(self):
        return _qft.Particle_p4(self)

    def q(self):
        return _qft.Particle_q(self)

    def t3(self):
        return _qft.Particle_t3(self)

    def pdgID(self):
        return _qft.Particle_pdgID(self)
    __swig_destroy__ = _qft.delete_Particle

# Register Particle in _qft:
_qft.Particle_swigregister(Particle)

def dSigmaDOmega(p1, p2, pdgID_out, cosTheta):
    return _qft.dSigmaDOmega(p1, p2, pdgID_out, cosTheta)
class s_partoncontent(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    upv = property(_qft.s_partoncontent_upv_get, _qft.s_partoncontent_upv_set)
    dnv = property(_qft.s_partoncontent_dnv_get, _qft.s_partoncontent_dnv_set)
    usea = property(_qft.s_partoncontent_usea_get, _qft.s_partoncontent_usea_set)
    dsea = property(_qft.s_partoncontent_dsea_get, _qft.s_partoncontent_dsea_set)
    str = property(_qft.s_partoncontent_str_get, _qft.s_partoncontent_str_set)
    sbar = property(_qft.s_partoncontent_sbar_get, _qft.s_partoncontent_sbar_set)
    chm = property(_qft.s_partoncontent_chm_get, _qft.s_partoncontent_chm_set)
    cbar = property(_qft.s_partoncontent_cbar_get, _qft.s_partoncontent_cbar_set)
    bot = property(_qft.s_partoncontent_bot_get, _qft.s_partoncontent_bot_set)
    bbar = property(_qft.s_partoncontent_bbar_get, _qft.s_partoncontent_bbar_set)
    glu = property(_qft.s_partoncontent_glu_get, _qft.s_partoncontent_glu_set)
    phot = property(_qft.s_partoncontent_phot_get, _qft.s_partoncontent_phot_set)

    def __init__(self):
        _qft.s_partoncontent_swiginit(self, _qft.new_s_partoncontent())
    __swig_destroy__ = _qft.delete_s_partoncontent

# Register s_partoncontent in _qft:
_qft.s_partoncontent_swigregister(s_partoncontent)
class c_mstwpdf(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    cont = property(_qft.c_mstwpdf_cont_get, _qft.c_mstwpdf_cont_set)
    xmin = property(_qft.c_mstwpdf_xmin_get, _qft.c_mstwpdf_xmin_set)
    xmax = property(_qft.c_mstwpdf_xmax_get, _qft.c_mstwpdf_xmax_set)
    qsqmin = property(_qft.c_mstwpdf_qsqmin_get, _qft.c_mstwpdf_qsqmin_set)
    qsqmax = property(_qft.c_mstwpdf_qsqmax_get, _qft.c_mstwpdf_qsqmax_set)
    mCharm = property(_qft.c_mstwpdf_mCharm_get, _qft.c_mstwpdf_mCharm_set)
    mBottom = property(_qft.c_mstwpdf_mBottom_get, _qft.c_mstwpdf_mBottom_set)
    alphaSQ0 = property(_qft.c_mstwpdf_alphaSQ0_get, _qft.c_mstwpdf_alphaSQ0_set)
    alphaSMZ = property(_qft.c_mstwpdf_alphaSMZ_get, _qft.c_mstwpdf_alphaSMZ_set)
    distance = property(_qft.c_mstwpdf_distance_get, _qft.c_mstwpdf_distance_set)
    tolerance = property(_qft.c_mstwpdf_tolerance_get, _qft.c_mstwpdf_tolerance_set)
    alphaSorder = property(_qft.c_mstwpdf_alphaSorder_get, _qft.c_mstwpdf_alphaSorder_set)
    alphaSnfmax = property(_qft.c_mstwpdf_alphaSnfmax_get, _qft.c_mstwpdf_alphaSnfmax_set)

    def update(self, x, q):
        return _qft.c_mstwpdf_update(self, x, q)

    def parton(self, flavour, x, q):
        return _qft.c_mstwpdf_parton(self, flavour, x, q)

    def __init__(self, filename, warn=False, fatal=True):
        _qft.c_mstwpdf_swiginit(self, _qft.new_c_mstwpdf(filename, warn, fatal))
    __swig_destroy__ = _qft.delete_c_mstwpdf

# Register c_mstwpdf in _qft:
_qft.c_mstwpdf_swigregister(c_mstwpdf)

