# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.2.0
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _dmc
else:
    import _dmc

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _dmc.delete_SwigPyIterator

    def value(self):
        return _dmc.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _dmc.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _dmc.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _dmc.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _dmc.SwigPyIterator_equal(self, x)

    def copy(self):
        return _dmc.SwigPyIterator_copy(self)

    def next(self):
        return _dmc.SwigPyIterator_next(self)

    def __next__(self):
        return _dmc.SwigPyIterator___next__(self)

    def previous(self):
        return _dmc.SwigPyIterator_previous(self)

    def advance(self, n):
        return _dmc.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _dmc.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _dmc.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _dmc.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _dmc.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _dmc.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _dmc.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _dmc:
_dmc.SwigPyIterator_swigregister(SwigPyIterator)
class vector_int(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _dmc.vector_int_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _dmc.vector_int___nonzero__(self)

    def __bool__(self):
        return _dmc.vector_int___bool__(self)

    def __len__(self):
        return _dmc.vector_int___len__(self)

    def __getslice__(self, i, j):
        return _dmc.vector_int___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _dmc.vector_int___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _dmc.vector_int___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _dmc.vector_int___delitem__(self, *args)

    def __getitem__(self, *args):
        return _dmc.vector_int___getitem__(self, *args)

    def __setitem__(self, *args):
        return _dmc.vector_int___setitem__(self, *args)

    def pop(self):
        return _dmc.vector_int_pop(self)

    def append(self, x):
        return _dmc.vector_int_append(self, x)

    def empty(self):
        return _dmc.vector_int_empty(self)

    def size(self):
        return _dmc.vector_int_size(self)

    def swap(self, v):
        return _dmc.vector_int_swap(self, v)

    def begin(self):
        return _dmc.vector_int_begin(self)

    def end(self):
        return _dmc.vector_int_end(self)

    def rbegin(self):
        return _dmc.vector_int_rbegin(self)

    def rend(self):
        return _dmc.vector_int_rend(self)

    def clear(self):
        return _dmc.vector_int_clear(self)

    def get_allocator(self):
        return _dmc.vector_int_get_allocator(self)

    def pop_back(self):
        return _dmc.vector_int_pop_back(self)

    def erase(self, *args):
        return _dmc.vector_int_erase(self, *args)

    def __init__(self, *args):
        _dmc.vector_int_swiginit(self, _dmc.new_vector_int(*args))

    def push_back(self, x):
        return _dmc.vector_int_push_back(self, x)

    def front(self):
        return _dmc.vector_int_front(self)

    def back(self):
        return _dmc.vector_int_back(self)

    def assign(self, n, x):
        return _dmc.vector_int_assign(self, n, x)

    def resize(self, *args):
        return _dmc.vector_int_resize(self, *args)

    def insert(self, *args):
        return _dmc.vector_int_insert(self, *args)

    def reserve(self, n):
        return _dmc.vector_int_reserve(self, n)

    def capacity(self):
        return _dmc.vector_int_capacity(self)
    __swig_destroy__ = _dmc.delete_vector_int

# Register vector_int in _dmc:
_dmc.vector_int_swigregister(vector_int)
class vector_double(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _dmc.vector_double_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _dmc.vector_double___nonzero__(self)

    def __bool__(self):
        return _dmc.vector_double___bool__(self)

    def __len__(self):
        return _dmc.vector_double___len__(self)

    def __getslice__(self, i, j):
        return _dmc.vector_double___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _dmc.vector_double___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _dmc.vector_double___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _dmc.vector_double___delitem__(self, *args)

    def __getitem__(self, *args):
        return _dmc.vector_double___getitem__(self, *args)

    def __setitem__(self, *args):
        return _dmc.vector_double___setitem__(self, *args)

    def pop(self):
        return _dmc.vector_double_pop(self)

    def append(self, x):
        return _dmc.vector_double_append(self, x)

    def empty(self):
        return _dmc.vector_double_empty(self)

    def size(self):
        return _dmc.vector_double_size(self)

    def swap(self, v):
        return _dmc.vector_double_swap(self, v)

    def begin(self):
        return _dmc.vector_double_begin(self)

    def end(self):
        return _dmc.vector_double_end(self)

    def rbegin(self):
        return _dmc.vector_double_rbegin(self)

    def rend(self):
        return _dmc.vector_double_rend(self)

    def clear(self):
        return _dmc.vector_double_clear(self)

    def get_allocator(self):
        return _dmc.vector_double_get_allocator(self)

    def pop_back(self):
        return _dmc.vector_double_pop_back(self)

    def erase(self, *args):
        return _dmc.vector_double_erase(self, *args)

    def __init__(self, *args):
        _dmc.vector_double_swiginit(self, _dmc.new_vector_double(*args))

    def push_back(self, x):
        return _dmc.vector_double_push_back(self, x)

    def front(self):
        return _dmc.vector_double_front(self)

    def back(self):
        return _dmc.vector_double_back(self)

    def assign(self, n, x):
        return _dmc.vector_double_assign(self, n, x)

    def resize(self, *args):
        return _dmc.vector_double_resize(self, *args)

    def insert(self, *args):
        return _dmc.vector_double_insert(self, *args)

    def reserve(self, n):
        return _dmc.vector_double_reserve(self, n)

    def capacity(self):
        return _dmc.vector_double_capacity(self)
    __swig_destroy__ = _dmc.delete_vector_double

# Register vector_double in _dmc:
_dmc.vector_double_swigregister(vector_double)
class vvector_double(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _dmc.vvector_double_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _dmc.vvector_double___nonzero__(self)

    def __bool__(self):
        return _dmc.vvector_double___bool__(self)

    def __len__(self):
        return _dmc.vvector_double___len__(self)

    def __getslice__(self, i, j):
        return _dmc.vvector_double___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _dmc.vvector_double___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _dmc.vvector_double___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _dmc.vvector_double___delitem__(self, *args)

    def __getitem__(self, *args):
        return _dmc.vvector_double___getitem__(self, *args)

    def __setitem__(self, *args):
        return _dmc.vvector_double___setitem__(self, *args)

    def pop(self):
        return _dmc.vvector_double_pop(self)

    def append(self, x):
        return _dmc.vvector_double_append(self, x)

    def empty(self):
        return _dmc.vvector_double_empty(self)

    def size(self):
        return _dmc.vvector_double_size(self)

    def swap(self, v):
        return _dmc.vvector_double_swap(self, v)

    def begin(self):
        return _dmc.vvector_double_begin(self)

    def end(self):
        return _dmc.vvector_double_end(self)

    def rbegin(self):
        return _dmc.vvector_double_rbegin(self)

    def rend(self):
        return _dmc.vvector_double_rend(self)

    def clear(self):
        return _dmc.vvector_double_clear(self)

    def get_allocator(self):
        return _dmc.vvector_double_get_allocator(self)

    def pop_back(self):
        return _dmc.vvector_double_pop_back(self)

    def erase(self, *args):
        return _dmc.vvector_double_erase(self, *args)

    def __init__(self, *args):
        _dmc.vvector_double_swiginit(self, _dmc.new_vvector_double(*args))

    def push_back(self, x):
        return _dmc.vvector_double_push_back(self, x)

    def front(self):
        return _dmc.vvector_double_front(self)

    def back(self):
        return _dmc.vvector_double_back(self)

    def assign(self, n, x):
        return _dmc.vvector_double_assign(self, n, x)

    def resize(self, *args):
        return _dmc.vvector_double_resize(self, *args)

    def insert(self, *args):
        return _dmc.vvector_double_insert(self, *args)

    def reserve(self, n):
        return _dmc.vvector_double_reserve(self, n)

    def capacity(self):
        return _dmc.vvector_double_capacity(self)
    __swig_destroy__ = _dmc.delete_vvector_double

# Register vvector_double in _dmc:
_dmc.vvector_double_swigregister(vvector_double)
class DiffusionMC(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, nt, idt, alpha=0.1):
        _dmc.DiffusionMC_swiginit(self, _dmc.new_DiffusionMC(nt, idt, alpha))

    def V(self, r):
        return _dmc.DiffusionMC_V(self, r)

    def ensureCapacity(self, index):
        return _dmc.DiffusionMC_ensureCapacity(self, index)

    def zeroAccumulators(self):
        return _dmc.DiffusionMC_zeroAccumulators(self)

    def oneMonteCarloStep(self, n):
        return _dmc.DiffusionMC_oneMonteCarloStep(self, n)

    def oneTimeStep(self, save_psi=False):
        return _dmc.DiffusionMC_oneTimeStep(self, save_psi)

    def getDIM(self):
        return _dmc.DiffusionMC_getDIM(self)

    def getNPSI(self):
        return _dmc.DiffusionMC_getNPSI(self)

    def getPsi(self):
        return _dmc.DiffusionMC_getPsi(self)

    def getESum(self):
        return _dmc.DiffusionMC_getESum(self)

    def getE2Sum(self):
        return _dmc.DiffusionMC_getE2Sum(self)

    def getRMax(self):
        return _dmc.DiffusionMC_getRMax(self)

    def getETHistory(self):
        return _dmc.DiffusionMC_getETHistory(self)

    def getNHistory(self):
        return _dmc.DiffusionMC_getNHistory(self)

    def getPsiHistory(self):
        return _dmc.DiffusionMC_getPsiHistory(self)

    def printout(self, out, skip=-1):
        return _dmc.DiffusionMC_printout(self, out, skip)

    def run(self, timeSteps, debug_every=100):
        return _dmc.DiffusionMC_run(self, timeSteps, debug_every)
    __swig_destroy__ = _dmc.delete_DiffusionMC

# Register DiffusionMC in _dmc:
_dmc.DiffusionMC_swigregister(DiffusionMC)

