# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.2.0
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _vmc
else:
    import _vmc

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _vmc.delete_SwigPyIterator

    def value(self):
        return _vmc.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _vmc.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _vmc.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _vmc.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _vmc.SwigPyIterator_equal(self, x)

    def copy(self):
        return _vmc.SwigPyIterator_copy(self)

    def next(self):
        return _vmc.SwigPyIterator_next(self)

    def __next__(self):
        return _vmc.SwigPyIterator___next__(self)

    def previous(self):
        return _vmc.SwigPyIterator_previous(self)

    def advance(self, n):
        return _vmc.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _vmc.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _vmc.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _vmc.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _vmc.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _vmc.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _vmc.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _vmc:
_vmc.SwigPyIterator_swigregister(SwigPyIterator)
class vector_double(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _vmc.vector_double_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _vmc.vector_double___nonzero__(self)

    def __bool__(self):
        return _vmc.vector_double___bool__(self)

    def __len__(self):
        return _vmc.vector_double___len__(self)

    def __getslice__(self, i, j):
        return _vmc.vector_double___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _vmc.vector_double___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _vmc.vector_double___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _vmc.vector_double___delitem__(self, *args)

    def __getitem__(self, *args):
        return _vmc.vector_double___getitem__(self, *args)

    def __setitem__(self, *args):
        return _vmc.vector_double___setitem__(self, *args)

    def pop(self):
        return _vmc.vector_double_pop(self)

    def append(self, x):
        return _vmc.vector_double_append(self, x)

    def empty(self):
        return _vmc.vector_double_empty(self)

    def size(self):
        return _vmc.vector_double_size(self)

    def swap(self, v):
        return _vmc.vector_double_swap(self, v)

    def begin(self):
        return _vmc.vector_double_begin(self)

    def end(self):
        return _vmc.vector_double_end(self)

    def rbegin(self):
        return _vmc.vector_double_rbegin(self)

    def rend(self):
        return _vmc.vector_double_rend(self)

    def clear(self):
        return _vmc.vector_double_clear(self)

    def get_allocator(self):
        return _vmc.vector_double_get_allocator(self)

    def pop_back(self):
        return _vmc.vector_double_pop_back(self)

    def erase(self, *args):
        return _vmc.vector_double_erase(self, *args)

    def __init__(self, *args):
        _vmc.vector_double_swiginit(self, _vmc.new_vector_double(*args))

    def push_back(self, x):
        return _vmc.vector_double_push_back(self, x)

    def front(self):
        return _vmc.vector_double_front(self)

    def back(self):
        return _vmc.vector_double_back(self)

    def assign(self, n, x):
        return _vmc.vector_double_assign(self, n, x)

    def resize(self, *args):
        return _vmc.vector_double_resize(self, *args)

    def insert(self, *args):
        return _vmc.vector_double_insert(self, *args)

    def reserve(self, n):
        return _vmc.vector_double_reserve(self, n)

    def capacity(self):
        return _vmc.vector_double_capacity(self)
    __swig_destroy__ = _vmc.delete_vector_double

# Register vector_double in _vmc:
_vmc.vector_double_swigregister(vector_double)
class QHO(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, Nin, alphain, MCStepsin):
        _vmc.QHO_swiginit(self, _vmc.new_QHO(Nin, alphain, MCStepsin))

    def zeroAccumulators(self):
        return _vmc.QHO_zeroAccumulators(self)

    def p(self, xTrial, x):
        return _vmc.QHO_p(self, xTrial, x)

    def ELocal(self, xi):
        return _vmc.QHO_ELocal(self, xi)

    def MetropolisStep(self):
        return _vmc.QHO_MetropolisStep(self)

    def oneMonteCarloStep(self):
        return _vmc.QHO_oneMonteCarloStep(self)

    def adjustStep(self):
        return _vmc.QHO_adjustStep(self)

    def doProductionSteps(self):
        return _vmc.QHO_doProductionSteps(self)

    def printout(self):
        return _vmc.QHO_printout(self)

    def normPsi(self):
        return _vmc.QHO_normPsi(self)

    def getPsiSquared(self):
        return _vmc.QHO_getPsiSquared(self)

    def getEAvg(self):
        return _vmc.QHO_getEAvg(self)

    def getEVariance(self):
        return _vmc.QHO_getEVariance(self)

    def getXMin(self):
        return _vmc.QHO_getXMin(self)

    def getXMax(self):
        return _vmc.QHO_getXMax(self)

    def getDx(self):
        return _vmc.QHO_getDx(self)
    __swig_destroy__ = _vmc.delete_QHO

# Register QHO in _vmc:
_vmc.QHO_swigregister(QHO)

